"""Add media_id to comments

Revision ID: 7e256acef07a
Revises: 8696d9138c1d
Create Date: 2026-05-07 08:41:10.843086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7e256acef07a'
down_revision: Union[str, None] = '8696d9138c1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('media_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_comments_media_id', 'comments', 'media', ['media_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_comments_media_id', 'comments', type_='foreignkey')
    op.drop_column('comments', 'media_id')
    # ### end Alembic commands ###
