"""Add structured location fields to memories

Revision ID: f3a2b1c0d9e8
Revises: ab6cbcc5b4a2
Create Date: 2026-05-07 14:22:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f3a2b1c0d9e8'
down_revision: Union[str, None] = 'ab6cbcc5b4a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('memories', sa.Column('admin1', sa.String(length=120), nullable=True))
    op.add_column('memories', sa.Column('admin2', sa.String(length=120), nullable=True))
    op.add_column('memories', sa.Column('admin3', sa.String(length=120), nullable=True))
    op.add_column('memories', sa.Column('village', sa.String(length=120), nullable=True))
    op.add_column('memories', sa.Column('address_text', sa.String(length=500), nullable=True))
    op.add_column('memories', sa.Column('place_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'place_name')
    op.drop_column('memories', 'address_text')
    op.drop_column('memories', 'village')
    op.drop_column('memories', 'admin3')
    op.drop_column('memories', 'admin2')
    op.drop_column('memories', 'admin1')
    op.drop_column('memories', 'country')
    # ### end Alembic commands ###
